
public class ch8o2 {
//  java.lang.ArithmeticException : / by zero
//  at ExceptionEx18.method2(ExceptionEx18.java:12)
//  at ExceptionEx18.method1(ExceptionEx18.java:8)
//  at ExceptionEx18.main(ExceptionEx18.java:4)
//  
//  a. . 위의 내용으로 예외가 발생했을 당시 호출스택에 존재했던 메서드를 알 수 있다
//  b. method2 , ExceptionEx18.java 12 . 예외가 발생한 위치는 메서드이며 파일의 12번째 줄이다
//  c.발생한 예외는 ArithmeticException 이며 0으로 나누어서 예외가 발생했다
//  d. method2 메서드가 method1 메서드를 호출하였고 그 위치는 ExceptionEx18.java 8 파일의 8번째 줄이다. --- method1이 method2를 호출한 것이다.
  
}
